// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Player struct {
	ID          int32
	Name        sql.NullString
	Gender      sql.NullString
	Age         sql.NullInt32
	TotalPizza  sql.NullInt32
	LoggedPizza sql.NullInt32
	Coins       sql.NullInt32
	DateCreated sql.NullTime
}
