// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Player struct {
	ID          int32
	Name        string
	Gender      string
	Age         int32
	TotalPizza  int32
	LoggedPizza int32
	Coins       int32
	DateCreated time.Time
}
