// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pizza.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createPizza = `-- name: CreatePizza :one
INSERT INTO pizza(player_id,logged_pizza,date_created) VALUES($1,$2,$3) RETURNING id, player_id, logged_pizza, date_created
`

type CreatePizzaParams struct {
	PlayerID    sql.NullInt32
	LoggedPizza int32
	DateCreated time.Time
}

func (q *Queries) CreatePizza(ctx context.Context, arg CreatePizzaParams) (Pizza, error) {
	row := q.db.QueryRowContext(ctx, createPizza, arg.PlayerID, arg.LoggedPizza, arg.DateCreated)
	var i Pizza
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.LoggedPizza,
		&i.DateCreated,
	)
	return i, err
}
