// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: players.sql

package database

import (
	"context"
	"time"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO player(name,gender,age,total_pizza,logged_pizza,coins,date_created) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id, name, gender, age, total_pizza, logged_pizza, coins, date_created
`

type CreatePlayerParams struct {
	Name        string
	Gender      string
	Age         int32
	TotalPizza  int32
	LoggedPizza int32
	Coins       int32
	DateCreated time.Time
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.Name,
		arg.Gender,
		arg.Age,
		arg.TotalPizza,
		arg.LoggedPizza,
		arg.Coins,
		arg.DateCreated,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.Age,
		&i.TotalPizza,
		&i.LoggedPizza,
		&i.Coins,
		&i.DateCreated,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM player WHERE id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePlayer, id)
	return err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, name, gender, age, total_pizza, logged_pizza, coins, date_created FROM player WHERE id = $1
`

func (q *Queries) GetPlayer(ctx context.Context, id int32) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.Age,
		&i.TotalPizza,
		&i.LoggedPizza,
		&i.Coins,
		&i.DateCreated,
	)
	return i, err
}

const getPlayers = `-- name: GetPlayers :many
SELECT id, name, gender, age, total_pizza, logged_pizza, coins, date_created FROM player
`

func (q *Queries) GetPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.Age,
			&i.TotalPizza,
			&i.LoggedPizza,
			&i.Coins,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE player
SET name = $1,gender = $2,age = $3,total_pizza = $4,logged_pizza = $5,coins = $6,date_updated = CURRENT_TIMESTAMP
WHERE id = $7
RETURNING id, name, gender, age, total_pizza, logged_pizza, coins, date_created
`

type UpdatePlayerParams struct {
	Name        string
	Gender      string
	Age         int32
	TotalPizza  int32
	LoggedPizza int32
	Coins       int32
	ID          int32
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, updatePlayer,
		arg.Name,
		arg.Gender,
		arg.Age,
		arg.TotalPizza,
		arg.LoggedPizza,
		arg.Coins,
		arg.ID,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.Age,
		&i.TotalPizza,
		&i.LoggedPizza,
		&i.Coins,
		&i.DateCreated,
	)
	return i, err
}
